# Generated by Django 3.2.22 on 2024-01-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0013_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='empresa',
        ),
        migrations.AddField(
            model_name='area',
            name='empresas',
            field=models.ManyToManyField(blank=True, related_name='areas_asociadas', to='AutenticacionApp.Empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='empresas_asociadas', to='AutenticacionApp.Area'),
        ),
    ]
