# Generated by Django 3.2.22 on 2024-01-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0015_verificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='perfil_completado',
            field=models.BooleanField(default=False, verbose_name='Perfil Completado'),
        ),
    ]
