# Generated by Django 3.2.22 on 2024-01-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0016_customuser_perfil_completado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='perfil_completado',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
