# Generated by Django 3.2.22 on 2024-01-15 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0017_auto_20240110_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AutenticacionApp.area', verbose_name='Área'),
        ),
    ]
