# Generated by Django 3.2.22 on 2024-01-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0018_customuser_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='area',
        ),
    ]
