# Generated by Django 3.2.22 on 2024-01-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0023_alter_area_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='empresa',
            name='giro',
            field=models.CharField(choices=[('construccion', 'Construcción'), ('comercial', 'Comercial o Comercio al por menor'), ('manufacturero', 'Manufacturero'), ('servicios', 'Servicios'), ('tecnologia', 'Tecnología de la Información (TI)'), ('alimenticio', 'Alimenticio'), ('educativo', 'Educativo'), ('salud', 'Salud y Cuidado Personal'), ('financiero', 'Financiero'), ('energia', 'Energía'), ('transporte', 'Transporte y Logística'), ('medios', 'Medios de Comunicación y Entretenimiento')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
