# Generated by Django 3.2.22 on 2024-01-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0024_auto_20240122_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nombre_empresa',
            new_name='razon_social',
        ),
    ]
