# Generated by Django 3.2.22 on 2024-01-22 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0025_rename_nombre_empresa_empresa_razon_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='numero_empleados',
            new_name='numero_colaboradores',
        ),
    ]
