# Generated by Django 3.2.22 on 2024-01-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0026_rename_numero_empleados_empresa_numero_colaboradores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='descripcion',
        ),
    ]
