# Generated by Django 3.2.22 on 2024-01-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0027_remove_area_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('', 'Selecciona el tipo de usuario'), ('Administrador', 'Administrador'), ('Alumno', 'Alumno'), ('Administrador Kabasis', 'Administrador Kabasis'), ('Asistente Administrativo', 'Asistente Administrativo')], default='', max_length=50, verbose_name='Tipo de Usuario'),
        ),
    ]
