# Generated by Django 3.2.22 on 2024-02-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0028_alter_customuser_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='giro',
            field=models.CharField(choices=[('Construccion', 'Construcción'), ('Comercial', 'Comercial o Comercio al por menor'), ('Manufacturero', 'Manufacturero'), ('Servicios', 'Servicios'), ('Tecnologia', 'Tecnología de la Información (TI)'), ('Alimenticio', 'Alimenticio'), ('Educativo', 'Educativo'), ('Salud', 'Salud y Cuidado Personal'), ('Financiero', 'Financiero'), ('Energia', 'Energía'), ('Transporte', 'Transporte y Logística'), ('Medios', 'Medios de Comunicación y Entretenimiento')], max_length=50),
        ),
    ]
