# Generated by Django 3.2.22 on 2024-02-01 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticacionApp', '0029_alter_empresa_giro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='empresas',
        ),
        migrations.AddField(
            model_name='area',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_relacionadas', to='AutenticacionApp.empresa'),
        ),
    ]
