# Generated by Django 3.2.22 on 2024-02-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0024_video_archivo_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='archivo_video',
        ),
    ]
